# Dockerfile.flask
FROM --platform=linux/amd64 python:3.12

# Set the working directory inside the container
WORKDIR /app

# Copy requirements.txt file to the working directory
COPY requirements.txt .

# Install app dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the entire project directory into the container
COPY . .

# Expose the port the app runs on
EXPOSE 5002

# Command to run the application
CMD ["python3", "orderBook.py"]
